### ISSUE TITLE
'charmap' codec can't decode byte 0x98 in position 1562: character maps to <undefined>

### ISSUE THREAD

**Issue by CaspianMaster** [nalgeon/iuliia-py#1]
![изображение](https://user-images.githubusercontent.com/49941322/81023842-5ddadc00-8e7a-11ea-8dff-faa83110540a.png)
Я не очень хорош в питоне, в чём может быть проблема?

**Comment by nalgeon** [comment]
Проблема в том, что я забыл о пользователях Windows с их умолчательной кодировкой cp1251. Исправлено в свежей версии:

```
pip install --upgrade iuliia
```
