### ISSUE TITLE
split() requires a non-empty pattern match

### ISSUE THREAD

**Issue by igroykt** [nalgeon/iuliia-py#3]
Приветствую.
Выполняю:
```python
#!/usr/bin/python3

#import tensorflow as tf
#print(tf.__version__)
import iuliia

source = "Юлия Щеглова"
iuliia.translate(source, schema=iuliia.MOSMETRO)
```

Результат:

> Traceback (most recent call last):
  File "./test.py", line 8, in <module>
    iuliia.translate(source, schema=iuliia.MOSMETRO)
  File "/usr/local/lib/python3.6/site-packages/iuliia/engine.py", line 17, in translate
    translated = (_translate_word(word, schema) for word in _split_sentence(source))
  File "/usr/local/lib/python3.6/site-packages/iuliia/engine.py", line 22, in _split_sentence
    return (word for word in SPLITTER.split(source) if word)
ValueError: split() requires a non-empty pattern match.

Python 3.6.8

**Comment by igroykt** [comment]
Если делать тоже самое в с командной строки (интерпретатор или приложение), то все корректно работает. Если запускать как скрипт, то выскакивает эта ошибка. Пока что вызываю через subprocess как временное решение.

**Comment by kthy** [comment]
`re.split()` does not support splitting on an empty pattern match in pythons 3.5 and 3.6, cf. [the documentation](https://docs.python.org/3.6/library/re.html#re.split). It works in [python 3.7 and above](https://docs.python.org/3.7/library/re.html#re.split).

**Comment by igroykt** [comment]
> 
> 
> `re.split()` does not support splitting on an empty pattern match in pythons 3.5 and 3.6, cf. [the documentation](https://docs.python.org/3.6/library/re.html#re.split). It works in [python 3.7 and above](https://docs.python.org/3.7/library/re.html#re.split).

Hi.
Thank for reply.
I don't know what you mean "empty pattern match". It shouldn't be empty. Tested on Python 3.6.8.
Anyway problem solved using Go implementation.

**Comment by kthy** [comment]
As far as I understand the docs, the problem isn't that it's empty, it's that it *could* be empty.

Anyway, @nalgeon, this seems to be a bug if support for Python 3.6 is needed (as specified in `pyproject.toml`). Otherwise the Python version could just be bumped and then this isn't a bug. :wink:

**Comment by nalgeon** [comment]
@kthy, thanks a lot! You are absolutely right. I've bumped the minimal Python version to 3.7.
